name: OWASP Juice Shop Development

on:
  push:
    branches:
      - dev

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  tf-plan:
    name: Plan
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Initialize terraform
      - name: Initialize
        run: |
          pushd ./infra
          terraform init
          popd

      # Terraform Plan
      - name: "Terraform Plan"
        id: plan
        run: |
          pushd ./infra
          terraform plan \
            -out=plan.tfplan \
            -var="project=${{env.PROJECT}}"
          popd
        continue-on-error: true