name: OWASP Juice Shop Development

on:
  push:
    branches:
      - dev

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  tf-plan:
    name: Plan
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      # Initialize terraform
      - name: Initialize
        run: |
          pushd ./infra
          terraform init
          popd

      # Terraform Plan
      - name: "Terraform Plan"
        id: plan
        run: |
          pushd ./infra
          terraform plan \
            -out=plan.tfplan \
            -var="project=${{env.PROJECT}}"
          popd

      # Upload plan file as artifact
      - name: "Upload Plan Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: infra/plan.tfplan